
name: CI/CD Pipeline

on:
  push:
    branches:
      - qa  # QA se ejecuta en pushes a la rama qa
  pull_request:
    branches:
      - main  # Producción se ejecuta en PRs hacia main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t jimmy1204/lenguajepyhton:${{ github.ref_name }} .
        docker push jimmy1204/lenguajepyhton:${{ github.ref_name }}
